#!/usr/bin/env python3
# fasta2tab
# print out table of sequences from FASTA file.
# ejr: 2022-10-12
# lmd: 2022-11-17
from fasta_utils import *
import fileinput
import signal

###############################################################################
### MAIN 
###############################################################################
def main():
    fh = fileinput.input()
    fasta = read_fasta(fh)
    print_seqtable(fasta)

###############################################################################
### Print FASTA Dictionary as seqtable to STDOUT
###############################################################################
def print_seqtable(fasta):
    for header in fasta:
        print(header, fasta[header], sep="\t")

###############################################################################
### RUN MAIN 
###############################################################################
if __name__ == "__main__":
    # this catches sigpipe errors so you don't get an error message if you tail of head output
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    main()
