#!/usr/bin/env python3
# fasta2len
# print table of lengths for sequences in FASTA file.
# ejr: 2022-11-16
# lmd: 2022-11-17

from fasta_utils import *
import fileinput
import signal

###############################################################################
### MAIN 
###############################################################################
def main():
    fh = fileinput.input()
    fasta = read_fasta(fh)
    print_lengths_table(fasta)
    
###############################################################################
### Print table of sequence lengths
###############################################################################
def print_lengths_table(fasta):
    print("seq_id\tseq_length")

    for header in fasta:
        slen = len(fasta[header])
        print(header, "\t", slen)

###############################################################################
### RUN MAIN 
###############################################################################
if __name__ == "__main__":
    # this catches sigpipe errors so you don't get an error message if you tail of head output
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    main()