#!/usr/bin/env python3
# fasta2tab
# ejr: 2022-10-12
#
import sys
import signal

# MAIN
def main():
    
    fasta = read_fasta(sys.stdin)
    print_fasta(fasta)

# READ FASTA FROM STDIN
def read_fasta(filename):
    header = ""
    fasta = {}

    for line in filename:
        line = line.rstrip()
        if (line[0] == ">"):
            header = line[1:]
            fasta[header] = []
        else:
            fasta[header].append(line)

    for header in fasta:
        fasta[header] = ''.join(fasta[header])

    return fasta

# PRINT FASTA TO STDOUT
def print_fasta(fasta):

    for header in fasta:
        print(header, fasta[header], sep="\t")

# RUN MAIN 
if __name__ == "__main__":
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    
    main()
