#!/usr/bin/env python3
# ejr - 2022-11-16
# last update: 2022-11-16
# INPUT: FASTA file on STDIN or with --file
# OUTPUT: Table of sequence lengths

from sequtils import *
import sys
import signal

###############################################################################
### MAIN ######################################################################
###############################################################################
def main():
    fasta = read_fasta(sys.stdin)
    print_lengths_table(fasta)
    
###############################################################################
# Print table of sequence lengths
###############################################################################
def print_lengths_table(fasta):
    print("seq_id\tseq_length")

    for header in fasta:
        slen = len(fasta[header])
        print(header, "\t", slen)

###############################################################################
### RUN MAIN ##################################################################
###############################################################################
if __name__ == "__main__":

    # this catches sigpipe errors so you don't get an error message if you tail of head output
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    main()