#!/usr/bin/env python3
# fasta2gc
# generate table of gc content for each sequence in FASTA file.
# ejr: 2022-11-16
# lmd: 2022-11-17

###############################################################################
### IMPORT ####################################################################
###############################################################################
from fasta_utils import *
import fileinput
import signal

###############################################################################
### MAIN ######################################################################
###############################################################################
def main():
    fh = fileinput.input()
    fasta = read_fasta(fh)
    print_gc_table(fasta)
    
###############################################################################
# Print table of GC content
###############################################################################
def print_gc_table(fasta):
    print("seq_id\tseq_gc")

    for header in fasta:
        gc = calc_gc(fasta[header]) * 100 
        print(header, "\t%0.2f" % gc)

###############################################################################
### RUN MAIN ##################################################################
###############################################################################
if __name__ == "__main__":

    # this catches sigpipe errors so you don't get an error message if you tail of head output
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    main()