#!/usr/bin/env python3
# tab2fasta
# convert table of sequences to FASTA file.
# ejr: 2022-10-12
# lmd: 2022-11-17
from fasta_utils import *
import fileinput
import sys
import signal

###############################################################################
### MAIN 
###############################################################################
def main():
    fh = fileinput.input()
    fasta = read_seqtable(fh)
    print_fasta(fasta)

###############################################################################
### Read seqtable filehandle into dictionary - seqtable = header\tseq
###############################################################################
def read_seqtable(fh):
    header = ""
    fasta = {}

    for line in fh:
        line = line.rstrip()
        fields = line.split("\t")
        fasta[fields[0]] = fields[1]

    return fasta

###############################################################################
### RUN MAIN 
###############################################################################
if __name__ == "__main__":
    # this catches sigpipe errors so you don't get an error message if you tail of head output
    signal.signal(signal.SIGPIPE, signal.SIG_DFL) 
    main()