#!/usr/bin/env python3
# tab2fasta
# ejr: 2022-10-12
# lmd: 2022-11-16
from sequtils import *
import fileinput
import sys
import signal

###############################################################################
### MAIN ######################################################################
###############################################################################
def main():
    fh = fileinput.input()
    fasta = read_seqtable(fh)
    print_fasta(fasta)

###############################################################################
### RUN MAIN ##################################################################
###############################################################################
if __name__ == "__main__":
    # this catches sigpipe errors so you don't get an error message if you tail of head output
    signal.signal(signal.SIGPIPE, signal.SIG_DFL) 
    main()
